posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, InputRequired
from datetime import datetime

class PostForm(FlaskForm):
	title = StringField('Title', validators = [DataRequired()])
	content = TextAreaField('Content', validators = [DataRequired()])
	submit = SubmitField('Post')

class AddCommentForm(FlaskForm):
	responder = StringField("Responder", validators=[InputRequired()])
	body = TextAreaField("Body", validators=[InputRequired()])
	submit = SubmitField("Post")

posts/routes.py
from flask import (render_template, url_for, flash,
				   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from Flask_Blog import db
from Flask_Blog.models import Post, Comment
from Flask_Blog.posts.forms import PostForm, AddCommentForm

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title = form.title.data, content = form.content.data, author = current_user)
		db.session.add(post)
		db.session.commit()
		flash('Your post has been created!','success')
		return redirect(url_for('main.home'))
	return render_template('create_post.html', title = 'New Post', form = form, legend='New Post')

@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
	post = Post.query.get_or_404(post_id)
	comments = Comment.query.all()
	return render_template('post.html', title=post.title, post=post, comments=comments)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	form = PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit()
		flash('Your post has been updated!', 'success')
		return redirect(url_for('posts.post', post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('create_post.html', title = 'Update Post', form = form, 
		legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Your post has been successfully deleted!', 'success')
	return redirect(url_for('main.home'))

@posts.route("/post/<int:post_id>/comment", methods=["GET", "POST"])
@login_required
def comment_post(post_id):
	ID = post_id
	form = AddCommentForm()
	if request.method == 'POST':
		if form.validate_on_submit():
			comment = Comment(body=form.body.data, responder=form.responder.data, post_id=ID)
			db.session.add(comment)
			db.session.commit()
			flash("Your comment has been added to the post", "success")
			return redirect(url_for("posts.post", post_id=ID))
	if request.method == 'GET':
		form.responder.data = "Anonymous"
	return render_template("comment_post.html", title="Comment Post", form=form, post_id=post_id)

users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from Flask_Blog import db, bcrypt
from Flask_Blog.models import User, Post
from Flask_Blog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from Flask_Blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username = form.username.data, email = form.email.data, password = hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Your account has been created, you are now able to log in!', 'success')
		return redirect(url_for('users.login'))

	return render_template('register.html', title = 'Register', form= form)


@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember = form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Login Unsuccessful. Please check email and password', 'danger')

	return render_template('login.html', title = 'Login', form= form)

@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route("/Account", methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated!', 'success')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data = current_user.email		
	
	image_file = url_for('static', filename='Profile_Pics/' + current_user.image_file)
	return render_template('account.html', title = 'account', image_file = image_file, form=form)

@users.route("/user/<string:username>")
def user_post(username):
	page = request.args.get('page', 1, type=int)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user)\
		.order_by(Post.date_posted.desc())\
		.paginate(page=page, per_page=3)
	return render_template('user_post.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions on how to reset your password, be sure check junk or spam inbox as needed', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash(f'Your password has been updated, you are now able to log in!', 'success')
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=form)

templates/FAQ1.html
{% extends 'layout.html' %}
{% block content %}
<div class="jumbotron pt-6">
	<h1 class="display-4">Reduce Your Risk from COVID-19</h1>
	<p class="lead Misc-Font-Color-2">COVID-19 spreads through direct contact with respiratory droplets or someone who is affected with the virus (e.g., when they cough or sneeze). These droplets can spread up to 2 metres or 6 feet.</p>
	<hr>

	<h3>Who is at increased risk?</h3>
	<h5>Risk for hospitalization or death from COVID-19 increases with:</h5>
	<ul style="margin:0; margin-left: 25px; padding:0; font-family: Arial, sans-serif; color:#495055; font-size:16px; line-height:22px;" align="left" type="disc">
		<li class="Misc-Font-Color-2">
			Age, as you get older the risk increases especially in older adults; 
		</li>
		<li class="Misc-Font-Color-2">
			Having a chronic medical condition including obesity, diabetes, lung/heart/kidney/liver diseases, stroke, high blood pressure, and conditions that weaken the immune system  (e.g., some cancers, untreated HIV/AIDS); 
		</li>
		<li class="Misc-Font-Color-2">
			Taking medications that weaken the immune system (e.g., chemotherapy, oral steroid medications). 
		</li>
	</ul>

	<br>
	<h3>Limit the number of people you are physically near</h3>
	<ul style="margin:0; margin-left: 25px; padding:0; font-family: Arial, sans-serif; color:#495055; font-size:16px; line-height:22px;" align="left" type="disc">
		<li class="Misc-Font-Color-2">
			Stay in touch with friends and family through phone, video chats, or text whenever possible. 
		</li>
		<li class="Misc-Font-Color-2">
			Work from home if possible.
		</li>
		<li class="Misc-Font-Color-2">
			See your health care providers virtually (e.g., doctors, physiotherapists) whenever possible.  
		</li>
	</ul>

	<br>
	<h3>Wear a mask and ensure those near you do too</h3>
	<ul style="margin:0; margin-left: 25px; padding:0; font-family: Arial, sans-serif; color:#495055; font-size:16px; line-height:22px;" align="left" type="disc">
		<li class="Misc-Font-Color-2">
			Wear a non-medical mask to help you from spreading infection to others.  
		</li>
		<li class="Misc-Font-Color-2">
			Wear a mask when you are indoors with people outside of your household and ensure those near you do too (assuming that you know them and it is safe to discuss mask use with them). 
		</li>
		<li class="Misc-Font-Color-2">
			Wear a mask whenever you are outdoors within 2 metres/6 feet of people outside of your household and ensure those near you do too.  
		</li>
	</ul>

	<br>
	<h3>Clean your hands frequently</h3>
	<ul style="margin:0; margin-left: 25px; padding:0; font-family: Arial, sans-serif; color:#495055; font-size:16px; line-height:22px;" align="left" type="disc">
		<li class="Misc-Font-Color-2">
			Wash hands often with soap and water. Don’t share hand towels.  
		</li>
		<li class="Misc-Font-Color-2">
			Carry and use an alcohol-based hand rub (60% - 90% alcohol) if soap and water are not available.  
		</li>
		<li class="Misc-Font-Color-2">
			Clean your hands whenever you touch objects or surfaces touched by others, and also if you touch another person. Avoid touching your face, and if you need to, clean your hands first.  
		</li>
	</ul>
	<br>


</div>
{% endblock %}

templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section bg-articleMode">
	<div class="d-flex">
    	<img class="rounded-circle account-img" src="{{ image_file }}">
  		<div class="mt-2">
      		<h2 class="Misc-Font-Color">{{ current_user.username }}</h2>
      		<p class="Misc-Font-Color"><small>{{ current_user.email }}</small></p>
  		</div>
	</div>
	<div>
		<form method="POST" action="" enctype="multipart/form-data">
			{{form.hidden_tag()}}
			<fieldset class="form-group">
				<legend class="article-metadata text-Mode">Account Info</legend>

				<div class="form-group text-Mode">
					{{ form.username.label(class="form-control-label") }}
					{% if form.username.errors %}
					<script>console.log("username - test")</script>
					{{ form.username(class="form-control form-control-lg alert-danger is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.username.errors %}
						<div>{{ error }}</div>
						{% endfor %}
					</div>
					{% else %}
					{{ form.username(class="form-control form-control-lg") }}
					{% endif %}
				</div>

				<div class="form-group text-Mode">
					{{ form.email.label(class="form-control-label") }}
					{% if form.email.errors %}
					<script>console.log("email - test")</script>
					{{ form.email(class="form-control form-control-lg alert-danger is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<div>{{ error }}</div>
						{% endfor %}
					</div>
					{% else %}
					{{ form.email(class="form-control form-control-lg") }}
					{% endif %}
				</div>
				<div class="form-group text-Mode mt-2">
					{{ form.picture.label(for="file-upload", class="custom-file-upload") }}</br>
					{{ form.picture(id="file-upload", type="file") }}
					<script type="text/javascript">
						document.getElementById("file-upload").onchange = function() {
							document.getElementById("uploadFile").value = this.value;
						};
					</script>
					<input id="uploadFile" placeholder="No File" disabled="disabled"/></br>
					{% if form.picture.errors %}
						{% for error in form.picture.errors %}
							<span class="text-danger">{{ error }}</span></br>
						{% endfor %}
					{% endif %}
				</div>
				<div class="form-group me-2 pt-2">
					{{ form.submit(class="btn btn-outline-Mode") }}
				</div>
			</fieldset>
		</form>
	</div>
</div>
{% endblock content %}

templates/comment_post.html
{% extends "layout.html"%}
{% block content %}
<div class="content-section bg-content-section">
    <form method="POST" action="{{url_for('posts.comment_post', post_id=post_id)}}">
        {{ form.hidden_tag() }}
        <fieldset class="form-group mb-1">
            <legend class="border-bottom mb-2 Misc-Font-Color">Add Comment</legend>
            <div class="form-group mb-1">
                {{ form.responder.label(class="form-control-label Misc-Font-Color mb-1") }}
                {% if form.responder.errors %}
                {{ form.responder(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.responder.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.responder(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.body.label(class="form-control-label Misc-Font-Color mb-1") }}
                {% if form.body.errors %}
                {{ form.body(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.body.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.body(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-Mode") }}
        </div>
    </form>
</div>
{% endblock content %}

templates/home.html
<!-- Allows inheritance from layout.html -->
{% extends "layout.html" %}

<!-- beggining of content block -->
{% block content %}
	{% for post in posts.items %}
		<!--
			Here a for loop is created where the object post loops 
			through the entries within the dictionary posts until all 
			entries have been processed by the following code curly 
			braces and % siginifies start and end of code block, 
			within this code block we are manipulating entries 
			within the posts dictionary using python 3
		-->
		<article class="content-section bg-articleMode d-flex">
			<img class="rounded-circle article-img" src="{{url_for('static', filename='Profile_Pics/' + post.author.image_file)}}">
			<div class="flex-grow-1">
				<div class="article-metadata">
					<a class="me-2 article-content" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
					<small class="article-content">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
				</div>
				<h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">																{{post.title }}</a></h2>
				<p class="article-content">{{ post.content }}</p>
			</div>
		</article>
	{% endfor %}
	{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
			{% if posts.page == page_num %}
				<a class="btn btn-Mode mb-4" href="{{ url_for('main.home', page=page_num) }}">
				{{ page_num }}</a>
			{% else %}
				<a class="btn btn-outline-Mode mb-4" href="{{ url_for('main.home', page=page_num) }}">
				{{ page_num }}</a>
			{% endif %}
		{% else %}
			...
		{% endif %}
	{% endfor %}
{% endblock content %}
<!-- end of content block -->

templates/layout.html
<!-- 
layout.html is a parent template from which our other html pages can inherit from.
Other pages are rendred such that they inherit layout.html and add their own elements
in the "content block" located in the body of layout.html
-->

<!--Typing 'html' + Tab will give a quick html template in sublime-->
<!DOCTYPE html>
<html>
<head>
	<!-- Begining of boot strap header -->

	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

	<!--Bootstrap 4.0 source files-->

	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	<!-- additional source links -->

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">


	<!-- allows us to use main.css in our project -->

	<link id="style1" rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">

	<!-- if / else statements in python -->

	{% if title %}
	<title>ON-COVID-Q&A-{{ title }}</title>
	{% else %}
	<title>ON-COVID-Q&A</title>
	{% endif %}

	<!-- Script -->
	<script>

	 // check for saved 'darkMode' in localStorage
	 let darkMode = localStorage.getItem('darkMode');
	 if(darkMode){
	 	console.log('darkMode existent:' + darkMode);
	 }

	 var a = document.getElementById("style1");
	 if (darkMode === 'enabled') {
	 	enableDarkMode(); 
	 }

	 function enableDarkMode(){
		  // 1. Add the class to the body
		  a.x = 'static/style2';
		  a.href="{{url_for('static', filename='style2.css')}}";
		  // 2. Update darkMode in localStorage
		  localStorage.setItem('darkMode', 'enabled');
		}

		function disableDarkMode(){
		  // 1. Remove the class from the body
		  a.x = 'static/main';
		  a.href="{{url_for('static', filename='main.css')}}";
		  // 2. Update darkMode in localStorage 
		  localStorage.setItem('darkMode', 'disabled');
		}

	function toggle() { // toggle
		
		// check for saved 'darkMode' in localStorage
		let darkMode = localStorage.getItem('darkMode');

		  // // if it not currently enabled, enable it
		  if (darkMode === 'disabled') {
		  	enableDarkMode();
		  // if it has been enabled, turn it off  
		} else {  
			disableDarkMode(); 
		}
	} 
</script>

</head>
<body>
	<!-- Navigation bar -->
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-modeColor fixed-top">
			<div class="container">
				<a class="navbar-brand mb-1" href="/">Ontario Covid-19 Q&A Forum</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav">

						<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
						<a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
					</div>
					<!-- Navbar Right Side -->
					<ul class="navbar-nav ms-auto">
						{% if current_user.is_authenticated %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.account') }}">Account</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Dark Mode</a>
						</li>
						{% else %}
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="#">Dark Mode</a>
						</li>
						{% endif %}
						<li class="nav-item mt-1">
							<label class="switch">
								<input type="checkbox">
								<span class="slider round" onclick="toggle()"></span>
							</label>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<!-- side bar -->
	<main role="main" class="container">
		<div class="row">
			<div class="col-md-8">
				{% with messages = get_flashed_messages(with_categories=true) %}
				{% if messages %}
				{% for category, message in messages %}
				<div class="alert alert-{{ category }}">
					{{ message }}
				</div>
				{% endfor %}
				{% endif %}
				{% endwith %}
				{% block content %}{% endblock %}
			</div>
			<div class="col-md-4">
				<div class="sidebar-section bg-articleMode">
					<h3>Frequently Asked Questions</h3>
					<p class='Misc-Font-Color'>Quick Resources for General Queries
						<div class="list-group list-group-custom">
							<a class="list-group-item" href="{{ url_for('main.FAQ1') }}">How to Protect Yourself from COVID-19</a>
							<a class="list-group-item" href="{{ url_for('main.FAQ2') }}">What is Physical Distancing?</a>
							<a class="list-group-item" href="{{ url_for('main.FAQ3') }}">mRNA Vaccines</a>
							<a class="list-group-item" href="{{ url_for('main.FAQ4') }}">How to Self-Isolate</a>
						</div>
					</p>
				</div>
			</div>
		</div>
	</main>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section bg-content-section">
		<form method="POST" action="">
			{{form.hidden_tag()}}
			<fieldset class="form-group">
				<legend class="article-metadata mb-4 text-Mode">Login</legend>

				<div class="form-group text-Mode">
					{{ form.email.label(class="form-control-label") }}
					
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg alert-danger is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-group text-Mode">
					{{ form.password.label(class="form-control-label") }}
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg alert-danger is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg") }}
					{% endif %}

				</div>
				<div class="form-check text-Mode pt-1">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>
			<div class="form-group me-2 pt-1">
				{{ form.submit(class="btn btn-outline-Mode") }}
			</div>
			<div class="pt-1">
				<small class="text-Mode me-2">
					<a class="text-Mode" href="{{url_for('users.reset_request')}}">Forgot Password? </a>
				</small>
			</div>
		</form>
		<div>
			<small class="text-Mode">
				Need An Account? <a class="me-2 text-Mode" href="{{ url_for('users.register') }}">Sign Up Now</a>
			</small>
		</div>
	</div>
{% endblock content %}

templates/post.html
<!-- Allows inheritance from layout.html -->
{% extends "layout.html" %}

<!-- beggining of content block -->
{% block content %}
<article class="content-section bg-articleMode d-flex">
	<img class="rounded-circle article-img" src="{{url_for('static', filename='Profile_Pics/' + post.author.image_file)}}">
	<div class="flex-grow-1">
		<div class="article-metadata">
			<a class="me-2 article-content" href="{{ url_for('users.user_post', username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="article-content">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
			{% if post.author == current_user %}
			<div>
				<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
				<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
			</div>
			{% endif %}
		</div>
		
		<h2 class="article-title">{{ post.title }}</h2>
		<p class="article-content">{{ post.content }}</p>
		<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.comment_post', post_id=post.id) }}">Post a Comment</a>
	</div>
</article>

<h2 class="lucida_console">Response Section</h2>
<hr>

<div>
	{% for comment in comments %}
		{% if comment.post_id == post.id %}
			<div class="content-section bg-articleMode">
				<h3 class="lucida_console"><u>Query Response</u></h3>
					<h5 class="lucida_console">Responder: {{ comment.responder }}</h5>
					<p class="article-content lucida_console">{{ comment.body }}</p>
			</div>
		{% endif %}
	{% endfor %}
</div>


<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
					<input class="btn btn-danger" type="submit" value="Delete">
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}
<!-- end of content block -->